### ISSUE TITLE
Uploading ODD from previous ROMA fails

### ISSUE THREAD

**Issue by catsmith** [TEIC/romajs#117]
I have an ODD (in xml) produced in the older/current version of ROMA which still loads fine into that version but I cannot load into the beta version. I get a completely blank page on the first attempt and after refreshing following the instructions on the home page I get a blue header  with only the 'start over' button active and the page below is completely blank. I can provide the ODD file if it is useful.

**Comment by raffazizzi** [comment]
Thanks for reporting this issue, @catsmith! Yes, please provide the ODD so I can investigate further.

**Comment by catsmith** [comment]
[TEI-NTMSS.zip](https://github.com/TEIC/romajs/files/5881686/TEI-NTMSS.zip)

@raffazizzi I have added as a zip as github would not let me upload the xml directly. If it doesn't work let me know and maybe I can email instead.

**Comment by raffazizzi** [comment]
Roma doesn't support RelaxNG elements at the moment, it only supports so called "pure" ODD. I'm working on RelaxNG support so that older ODDs can be imported as well, but it'll take a while. Roma is supposed to give a warning when ODDs with RelaxNG in them are uploaded, but for some reason this ODD wasn't caught, so I'm going to look into that.

Fortunately, if you wanted to use your ODD with the new Roma, you just need to make a small change. Find this code:

```xml
<rng:text xmlns:rng="http://relaxng.org/ns/structure/1.0"/>
```
and replace it with:
```xml
<dataRef name="text"/>
```

The ODD should then be imported into new Roma without error.
