### ISSUE TITLE
Duplicate attribute "style" and "rendition" errors

### ISSUE THREAD

**Issue by eafentoulidou** [TEIC/romajs#129]
Hello!
I cannot validate the rng schema I create with roma because of the error messages "Duplicate attribute "style"" and "Duplicate attribute "rendition"".
I can only validate it by manually deleting the doublets
   <ref name="tei_att.global.rendition.attribute.style"/>
   <ref name="tei_att.global.rendition.attribute.rendition"/>

I get these messages in every element definition. Here is an example of how it looks like fresh from downloading, before my manual deletions:

 <define name="tei_timeline">
 <element name="timeline">
         <a:documentation xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0">(timeline) provides a set of ordered points in time which can be linked to elements of a spoken text to create a temporal alignment of that text. [16.4.2. Placing Synchronous Events in Time]</a:documentation>
         <oneOrMore>
            <ref name="tei_when"/>
         </oneOrMore>
         <ref name="tei_att.global.attribute.style"/>
         <ref name="tei_att.global.attribute.rendition"/>
         <ref name="tei_att.global.attribute.xmlid"/>
         <ref name="tei_att.global.rendition.attribute.style"/>
         <ref name="tei_att.global.rendition.attribute.rendition"/>
         <ref name="tei_att.global.responsibility.attribute.cert"/>
         <ref name="tei_att.global.responsibility.attribute.resp"/>
         <ref name="tei_att.global.source.attribute.source"/>
         <optional>
            <attribute name="origin">
               <a:documentation xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0">designates the origin of the timeline, i.e. the time at which it begins.</a:documentation>
               <data type="anyURI"/>
            </attribute>
         </optional>
         <optional>
            <attribute name="unit">
               <a:documentation xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0">specifies the unit of time corresponding to the <code xmlns="http://www.w3.org/1999/xhtml">@interval</code> value of the timeline or of its constituent points in time.</a:documentation>
               <choice>
                  <value>s</value>
                  <a:documentation xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0"/>
               </choice>
            </attribute>
         </optional>
         <empty/>
      </element>
</define>

Thanks,
Eirini

**Comment by martinascholger** [comment]
@eafentoulidou could you please provide us with the ODD?

**Comment by eafentoulidou** [comment]
Hallo! Sorry for the delay. Here is the ODD (converted in txt)
[Afentoulidou_odd.txt](https://github.com/TEIC/romajs/files/6647626/Afentoulidou_odd.txt)
Thank you very much!

**Comment by lb42** [comment]
This ODD must have been generated (by Versioning Machine) some time ago, when the attributes @style and @rend were supplied directly by the att.global class, rather than indirectly via att.global.rendition. The lines
~~~
 <classSpec ident="att.global" module="tei" type="atts" mode="change">
               <attList>
                  <attDef ident="xml:lang" mode="delete"/>
                  <attDef ident="style" mode="delete"/>
                  <attDef ident="rendition" mode="delete"/>
                  <attDef ident="xml:base" mode="delete"/>
                  <attDef ident="xml:space" mode="delete"/>
               </attList>
            </classSpec>
~~~
have no effect on the attributes  @style and @rendition since they are not members of att,global. Consequently, they are not deleted, and you get two definitions for them.
I'd suggest regenerating your ODD with a more uptodate version of the Guidelines! Alternatively, you could replace the lines quoted with the following, which delete the attributes from the right classes
~~~~
 <classSpec ident="att.global.rendition" module="tei" type="atts" mode="change">
               <attList>
                  <attDef ident="style" mode="delete"/>
                  <attDef ident="rendition" mode="delete"/>
                   </attList>
            </classSpec>
          <classSpec ident="att.global" module="tei" type="atts" mode="change">
           <attList>
            <attDef ident="xml:lang" mode="delete"/>
            <attDef ident="xml:base" mode="delete"/>
            <attDef ident="xml:space" mode="delete"/>
           </attList>
          </classSpec>
~~~~
but you will then hit a further problem because the attribute @hand is defined twice as well: again, it's because the class supplying this attribute has changed.

And for some reason I don't understand, your ODD tries to include the @wit attribute twice
~~~~
     <attRef name="wit" class="att.rdgPart"/>
                <attRef name="wit" class="att.witnessed"/>
~~~~
My revised version of your ODD is attached: it does generate a valid RNG schema, but whether it does what you want I am not sure!
[Afentoulidou_odd.zip](https://github.com/TEIC/romajs/files/6655334/Afentoulidou_odd.zip)

**Comment by eafentoulidou** [comment]
Thank you very much for your helpful answer.

> My revised version of your ODD is attached: it does generate a valid RNG schema, but whether it does what you want I am not sure!
> [Afentoulidou_odd.zip](https://github.com/TEIC/romajs/files/6655334/Afentoulidou_odd.zip)

Yes, your ODD solves the issues. I took it as basis for further customisation. Thanks!
