### ISSUE TITLE
local source reference on `schemaSpec` of compiled ODD

### ISSUE THREAD

**Issue by bwbohl** [TEIC/romajs#152]
When I upload an ODD (without `schemaSpec/@source`) and then download it as compiled ODD the `schemaSpec/@source` is set to `/usr/share/xml/tei/odd/p5subset.xml`. This seems to be a local source on the server, but I think it would be better set to `https://www.tei-c.org/Vault/P5/current/xml/tei/odd/p5subset.xml` or, even better, the actual current version in the Vault, today being: `https://www.tei-c.org/Vault/P5/4.6.0/xml/tei/odd/p5subset.xml`.

I think the resolved "current" address would be best. Because then the version compiled against (if not specified in the original ODD) would be accounted for.

**Comment by raffazizzi** [comment]
Thanks for reporting this problem. The ODD compilation process is handled by [TEIGarage](https://github.com/TEIC/TEIGarage), which calls the [TEI Stylesheets](https://github.com/teic/stylesheets) to handle the ODD compilation process. `/usr/share/xml/tei/odd/p5subset.xml` is likely the default value set by either TEIGarage or the Stylesheets. If TEIGarage allows the change this value via their RESTful API, then I will be able to address it in Roma. Otherwise this will be an issue for TEIGarage and/or the TEI Stylesheets. Will investigate.

**Comment by raffazizzi** [comment]
It doesn't seem to be possible to set this parameter in TEIGarage. I opened an issue there: https://github.com/TEIC/TEIGarage/issues/90.
