### ISSUE TITLE
Roma rejecting @source in ODDs

### ISSUE THREAD

**Issue by pml-gh** [TEIC/romajs#175]
Got the following message when trying to upload my schema:

Error: RomaJS does not support TEI ODD with @source attributes at the moment.

**Comment by raffazizzi** [comment]
Hello @pml-gh, the error tells the truth: Roma is not able to handle ODDs that contain `@source` attributes because ithat would require loading additional files referred by the URIs in `@source` attributes. Support for this feature is not planned for the time being — it would be rather complex. I would suggest verifying whether your ODD can be expressed without it if you need to rely on Roma for your customization efforts.
