### ISSUE TITLE
Editing value desc of Attributes causes unresponsive blank page

### ISSUE THREAD

**Issue by aklsdm** [TEIC/romajs#73]
If I want to edit the value description of Attributes by clicking the text box and starting to type, the page goes blank and cannot be reloaded. The URL remains unaccessible in that browser after this. Tested on Chrome and Safari.

(@bleekere)

**Comment by raffazizzi** [comment]
Hello - sorry for the delay in addressing this. I believe it should be fixed now! Let me know if not.

**Comment by raffazizzi** [comment]
@aklsdm if for some reason your browser still won't load the page at all, it's because it has stored corrupt data. I'm going to upload a new release that avoids this problem shortly, but in the meantime you can either access the site from incognito mode, or turn on the browser console (usually with F12) and run this command: `localStorage.clear()` then go back to romabeta.tei-c.org
